Assignment 7.1 --> 
Your objective is to implement the K-Nearest Neighbors (KNN) algorithm
with k=3. Use this algorithm to predict the income value, with the given
input value X=22.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    {
        "Age" : [21,20,22,22,23,21,25,30,31] , 
        "Income" : [60,55,60,61,65,62,65,70,68]
    }
)
df

Age  Income
0   21      60
1   20      55
2   22      60
3   22      61
4   23      65
5   21      62
6   25      65
7   30      70
8   31      68

In [3]:
from sklearn.neighbors import KNeighborsRegressor

In [4]:
knn_reg = KNeighborsRegressor(n_neighbors=3)

In [5]:
knn_reg.fit(df[['Age']] , df['Income'])

KNeighborsRegressor(n_neighbors=3)

In [6]:
x = [[22]]
knn_reg.predict(x)

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([60.33333333])

Additionally, compare the predicted outcomes of the KNN algorithm
with Linear Regression results.

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
lr = LinearRegression().fit(df[['Age']] , df['Income'])


In [9]:
lr.predict(x)

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([60.97068966])

Assignment 7.2 --> KNN for Regression
1. Import data set
2. Separate X (Gender, Height) and Y (y=Weight).
3. Train = 70%, Test = 30%
4. Apply Linear Regression
5. Evaluate the Model (Testing and training Accuracy, MSE for testing)
6. Apply KNN Regressor: Scikit-Learn Link
7. Evaluate the Model (Testing and training Accuracy, MSE for testing)
8. Compare KNN & Linear Regression with the KNN Model and Linear regression as well.

In [10]:
data_reg = pd.read_csv('F:\\download\\weight-height.csv')
data_reg.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [11]:
x = data_reg.drop(columns='Weight')
y = data_reg[['Weight']]

Feature encoding and Feature scaling

In [12]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
le = LabelEncoder()
scaler = MinMaxScaler()

In [13]:
x['Gender']=le.fit_transform(x[['Gender']])
x = scaler.fit_transform(x)

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
x

array([[1.        , 0.74439877],
       [1.        , 0.54832843],
       [1.        , 0.75458291],
       ...,
       [0.        , 0.42453987],
       [0.        , 0.49599516],
       [0.        , 0.24406373]])

In [15]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.3,random_state=112)

In [16]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5988, 2)
(2567, 2)
(5988, 1)
(2567, 1)


In [17]:
lin_reg = LinearRegression().fit(x_train , y_train)

In [18]:
lin_reg_ans_for_test = lin_reg.predict(x_test)
lin_reg_ans_for_train = lin_reg.predict(x_train)

In [20]:
y_train

Weight
1035  207.542121
1127  205.052685
4815  186.291276
4655  209.482125
6239  131.702314
...          ...
684   195.189930
5317  131.661110
2369  139.411145
7642  166.637555
232   235.926061

[5988 rows x 1 columns]

In [25]:
from sklearn.metrics import mean_squared_error,r2_score


error_train = mean_squared_error(y_train , lin_reg_ans_for_train)
error_test = mean_squared_error(y_test , lin_reg_ans_for_test)
print("Training Error: ", error_train)
print("Testing Error: ", error_test)

accuracy_train = r2_score(y_train , lin_reg_ans_for_train)
accuracy_test = r2_score(y_test , lin_reg_ans_for_test)
print("Training Accuracy: ", accuracy_train)
print("Testing Accuracy: ", accuracy_test)

Training Error:  101.68990974298215
Testing Error:  105.16868546533102
Training Accuracy:  0.9007072648264776
Testing Accuracy:  0.8981526254070041


KNN regression

In [26]:
knn_reg_new = KNeighborsRegressor(n_neighbors=5)
knn_reg_new.fit(x_train, y_train)
knn_reg_ans_for_test = knn_reg_new.predict(x_test)
knn_reg_ans_for_train = knn_reg_new.predict(x_train)

In [27]:
error_train = mean_squared_error(y_train , knn_reg_ans_for_train)
error_test = mean_squared_error(y_test , knn_reg_ans_for_test)
print("Training Error: ", error_train)
print("Testing Error: ", error_test)

accuracy_train = r2_score(y_train , knn_reg_ans_for_train)
accuracy_test = r2_score(y_test , knn_reg_ans_for_test)
print("Training Accuracy: ", accuracy_train)
print("Testing Accuracy: ", accuracy_test)

Training Error:  83.11155834724819
Testing Error:  124.26610300230769
Training Accuracy:  0.9188476617425497
Testing Accuracy:  0.8796583195302944


KNN for Classification
1. Import data set
2. Separate X and Y. (y=Gender)
3. Train = 70%, Test = 30%
4. Apply KNN Classifier
5. Evaluate the Model by only Accuracy.
6. Apply KNN Classifier: Scikit-Learn Link

In [28]:
data_class = pd.read_csv('F:\\download\\weight-height.csv')
data_class.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [32]:
x = data_class.drop(columns='Gender')
y = data_class[['Gender']]

In [33]:
y['Gender']=le.fit_transform(y[['Gender']])

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_1488\568562139.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['Gender']=le.fit_transform(y[['Gender']])


In [34]:
y

Gender
0          1
1          1
2          1
3          1
4          1
...      ...
8550       0
8551       0
8552       0
8553       0
8554       0

[8555 rows x 1 columns]

In [35]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.3 , random_state=123)

In [36]:
from sklearn.neighbors import KNeighborsClassifier
knn_class = KNeighborsClassifier(n_neighbors=3)
knn_class.fit(x_train, y_train)
knn_class_ans = knn_class.predict(x_test)

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, knn_class_ans)

0.9006622516556292